name: Build and Deploy

on:
  push:
    branches: ["main", "dev", "test"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          # cache: 'yarn' # Not required as only running on a single version

      - run: yarn --non-interactive --frozen-lockfile
      - run: yarn run build
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')
        with:
          name: public
          path: public

  deploy:
    environment: ${{ github.ref_name }} # This is dodgy, should use composite action instead
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test')
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - uses: reggionick/s3-deploy@v3
        with:
          folder: public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: eu-west-2
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          filesToInclude: ".*/*,*/*,**"
