name: Build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: '!(github.event_name == "pull_request" && github.pull_request.base.ref == "dev")'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          upload: false
