name: Test Build

on:
  pull_request:
    branches: ["main", "dev", "test"]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == push && github.pull_request.base.ref == dev }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          upload_condition: false
